# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyStylingApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyStylingApp

  target 'MyStylingApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyStylingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyStylingApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyStylingApp-tvOS

  target 'MyStylingApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
